
#INSERT INTO ETAGE VALUE (0,3,3);
#INSERT INTO ETAGE VALUE (1,3,3);
/*
#INSERT INTO PARKPLATZ (EtageNummer,Typ) VALUE  (0,'AUTO');
#INSERT INTO PARKPLATZ (EtageNummer,Typ) VALUE (0,'MOTORRAD');

#INSERT INTO PARKPLATZ  (EtageNummer,Typ)  VALUE (1,'AUTO');
#INSERT INTO PARKPLATZ   (EtageNummer,Typ)  VALUE (1,'MOTORRAD');

#INSERT INTO PARKPLATZ   (EtageNummer,Typ)  VALUE (0,'AUTO');
#INSERT INTO PARKPLATZ   (EtageNummer,Typ)  VALUE (1,'MOTORRAD');

#INSERT INTO FAHRZEUG   VALUE ('auto1',1);
#INSERT INTO FAHRZEUG  VALUE ('auto2',2);


#INSERT INTO FAHRZEUG VALUE ('Motorad1',3);
#INSERT INTO FAHRZEUG VALUE ('Motorad2',4);

*/
